// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTimelineNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTimelineNote'](arg1, arg2, arg3);
}

export function BackupDatabaseFile() {
  return window['go']['main']['App']['BackupDatabaseFile']();
}

export function CreateApplication(arg1) {
  return window['go']['main']['App']['CreateApplication'](arg1);
}

export function DeleteApplication(arg1) {
  return window['go']['main']['App']['DeleteApplication'](arg1);
}

export function ExportApplicationsCSV() {
  return window['go']['main']['App']['ExportApplicationsCSV']();
}

export function ExportApplicationsJSON() {
  return window['go']['main']['App']['ExportApplicationsJSON']();
}

export function GetApplicationDetail(arg1) {
  return window['go']['main']['App']['GetApplicationDetail'](arg1);
}

export function GetApplications(arg1) {
  return window['go']['main']['App']['GetApplications'](arg1);
}

export function GetDatabasePath() {
  return window['go']['main']['App']['GetDatabasePath']();
}

export function GetRecentApplications(arg1) {
  return window['go']['main']['App']['GetRecentApplications'](arg1);
}

export function GetScheduleEvents() {
  return window['go']['main']['App']['GetScheduleEvents']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function ImportApplicationsFile() {
  return window['go']['main']['App']['ImportApplicationsFile']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RestoreDatabaseFile() {
  return window['go']['main']['App']['RestoreDatabaseFile']();
}

export function SetInterviewDate(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetInterviewDate'](arg1, arg2, arg3);
}

export function UpdateApplication(arg1) {
  return window['go']['main']['App']['UpdateApplication'](arg1);
}

export function UpdateStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateStatus'](arg1, arg2, arg3);
}
